name: 'Default environment variables'

on:
  push:

jobs:
  mainjob:
    name: 'Print the Default Github vars'
    runs-on: ubuntu-latest

    steps:
    - name: print-valus-of-env-vars
      run:
        echo "$GITHUB_ACTION"
        echo "$GITHUB_ENV"
        echo "$GITHUB_API_URL"
        echo "$GITHUB_JOB"
        echo "$GITHUB_PATH"
        echo "$GITHUB_STEP_SUMMARY"
        echo "$GITHUB_REPOSITORY"
        echo "$GITHUB_REPOSITORY_OWNER"
        echo "$GITHUB_RUN_ID"
        echo "$GITHUB_RUN_NUMBER"
        echo "$GITHUB_WORKFLOW"
        echo "$GITHUB_SERVER_URL"
        echo "$RUNNER_NAME"
        echo "$RUNNER_OS"  