name: Passing value between steps

on:
  workflow_dispatch:

jobs:
  passing-values-bw-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value using ENV var
        run: echo "variableName=this-is-value" >> $GITHUB_ENV

      - name: Create Variables
        id: var-source-step
        run: |
          echo "Performing a random task"
          echo "var1-name=${{ env.variableName }}" >> $GITHUB_OUTPUT
          echo "var2-date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get the values
        run: |
          echo "Printing the values"
          echo "variableName: ${{ env.variableName }}"
          echo "var1-name: ${{ steps.var-source-step.outputs.var1-name }}"
          echo "var2-date: ${{ steps.var-source-step.outputs.var2-date }}"
